version: 2

sources:
  - name: bronze_source      # This is the source name (used in `source('public', ...)`)
    database: jr_lab_db1
    schema: bronze    # This is the actual Snowflake schema name
    tables:
      - name: nations_raw
      - name: regions_raw
      - name: orders_raw
      - name: customers_raw

